# Type stubs for espn_api.football
# This file provides basic type information for the ESPN API

from __future__ import annotations

from typing import Any

class League:
    def __init__(
        self,
        league_id: int,
        year: int,
        espn_s2: str | None = None,
        swid: str | None = None,
        debug: bool = False,
    ) -> None: ...
    @property
    def teams(self) -> list[Team]: ...
    @property
    def current_week(self) -> int: ...

class Team:
    def __init__(self) -> None: ...
    @property
    def team_name(self) -> str | None: ...
    @property
    def team_abbrev(self) -> str | None: ...
    @property
    def team_id(self) -> int: ...
    @property
    def owner(self) -> str | dict[str, Any] | list[dict[str, Any]] | Any: ...
    @property
    def owners(self) -> str | dict[str, Any] | list[dict[str, Any]] | Any: ...
    @property
    def points_for(self) -> float: ...
    @property
    def points_against(self) -> float: ...
    @property
    def wins(self) -> int: ...
    @property
    def losses(self) -> int: ...
    @property
    def schedule(self) -> list[Any]: ...

class Box:
    def __init__(self) -> None: ...
    @property
    def home_team(self) -> Team: ...
    @property
    def away_team(self) -> Team: ...
    @property
    def home_score(self) -> float: ...
    @property
    def away_score(self) -> float: ...
